services:
  websockify:
    image: registry.fit2cloud.com/north/websockify:latest
    container_name: websockify
    ports:
      - "0.0.0.0:6080:6080"
    restart: always
    mem_limit: 1024m
    depends_on:
      vm-service:
        condition: service_healthy
    networks:
      - cmp-network
